
spring:
    freemarker:
        cache: false
    application:
        name: ComponentDevelopment
    servlet:
        multipart:
            max-file-size: 3GB
            max-request-size: 3GB
    thymeleaf:
        encoding: UTF-8
        cache: true
upload:
    dir: D:\\video\\
    download_dir: D:\\javaPrj\\video\\

server:
    port: 5432




